"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var app_1 = require("./app");
var dataManager_1 = require("./dataManager");
var ResultTableManager_1 = require("./ResultTableManager");
var SvgManager_1 = require("./SvgManager");
var dataManager = new dataManager_1.default();
var table = document.getElementById("result-table");
var tableManager = new ResultTableManager_1.default(table);
var svgManager = new SvgManager_1.default(dataManager, tableManager);
new app_1.default(tableManager, dataManager, svgManager).initializeListeners();
